version: '3.6'
services:

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    environment:
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MagicWord"
      xpack.security.enabled: true
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node 
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  Logstash:
    user: root
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - /var/lib/docker/containers/:/logcontainers:ro
    command: bash -c "yum install git -y && git clone https://github.com/bettercallsaullegal/elk-configuration.git && logstash -f elk-configuration/logstash/logstash.conf"
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - elk
volumes:
  elastic_data: {}

networks:
  elk:
